/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LehrmaterialienRouteImport } from './routes/lehrmaterialien'
import { Route as PruefungszentrumFindenRouteImport } from './routes/pruefungszentrum-finden'
import { Route as QualifizierungRouteImport } from './routes/qualifizierung'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SprachpruefungenRouteImport } from './routes/sprachpruefungen'
import { Route as TrainingsangeboteRouteImport } from './routes/trainingsangebote'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ZertifikatPruefenRouteImport } from './routes/zertifikat-pruefen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LehrmaterialienRoute = LehrmaterialienRouteImport.update({
  id: '/lehrmaterialien',
  path: '/lehrmaterialien',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungszentrumFindenRoute = PruefungszentrumFindenRouteImport.update({
  id: '/pruefungszentrum-finden',
  path: '/pruefungszentrum-finden',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifizierungRoute = QualifizierungRouteImport.update({
  id: '/qualifizierung',
  path: '/qualifizierung',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SprachpruefungenRoute = SprachpruefungenRouteImport.update({
  id: '/sprachpruefungen',
  path: '/sprachpruefungen',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsangeboteRoute = TrainingsangeboteRouteImport.update({
  id: '/trainingsangebote',
  path: '/trainingsangebote',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ZertifikatPruefenRoute = ZertifikatPruefenRouteImport.update({
  id: '/zertifikat-pruefen',
  path: '/zertifikat-pruefen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktuelles': typeof AktuellesRoute
  '/campus': typeof CampusRoute
  '/kontakt': typeof KontaktRoute
  '/lehrmaterialien': typeof LehrmaterialienRoute
  '/pruefungszentrum-finden': typeof PruefungszentrumFindenRoute
  '/qualifizierung': typeof QualifizierungRoute
  '/sitemap': typeof SitemapRoute
  '/sprachpruefungen': typeof SprachpruefungenRoute
  '/trainingsangebote': typeof TrainingsangeboteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/zertifikat-pruefen': typeof ZertifikatPruefenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktuelles': typeof AktuellesRoute
  '/campus': typeof CampusRoute
  '/kontakt': typeof KontaktRoute
  '/lehrmaterialien': typeof LehrmaterialienRoute
  '/pruefungszentrum-finden': typeof PruefungszentrumFindenRoute
  '/qualifizierung': typeof QualifizierungRoute
  '/sitemap': typeof SitemapRoute
  '/sprachpruefungen': typeof SprachpruefungenRoute
  '/trainingsangebote': typeof TrainingsangeboteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/zertifikat-pruefen': typeof ZertifikatPruefenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktuelles': typeof AktuellesRoute
  '/campus': typeof CampusRoute
  '/kontakt': typeof KontaktRoute
  '/lehrmaterialien': typeof LehrmaterialienRoute
  '/pruefungszentrum-finden': typeof PruefungszentrumFindenRoute
  '/qualifizierung': typeof QualifizierungRoute
  '/sitemap': typeof SitemapRoute
  '/sprachpruefungen': typeof SprachpruefungenRoute
  '/trainingsangebote': typeof TrainingsangeboteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/zertifikat-pruefen': typeof ZertifikatPruefenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktuelles'
    | '/campus'
    | '/kontakt'
    | '/lehrmaterialien'
    | '/pruefungszentrum-finden'
    | '/qualifizierung'
    | '/sitemap'
    | '/sprachpruefungen'
    | '/trainingsangebote'
    | '/ueber-uns'
    | '/zertifikat-pruefen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aktuelles'
    | '/campus'
    | '/kontakt'
    | '/lehrmaterialien'
    | '/pruefungszentrum-finden'
    | '/qualifizierung'
    | '/sitemap'
    | '/sprachpruefungen'
    | '/trainingsangebote'
    | '/ueber-uns'
    | '/zertifikat-pruefen'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktuelles'
    | '/campus'
    | '/kontakt'
    | '/lehrmaterialien'
    | '/pruefungszentrum-finden'
    | '/qualifizierung'
    | '/sitemap'
    | '/sprachpruefungen'
    | '/trainingsangebote'
    | '/ueber-uns'
    | '/zertifikat-pruefen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AktuellesRoute: typeof AktuellesRoute
  CampusRoute: typeof CampusRoute
  KontaktRoute: typeof KontaktRoute
  LehrmaterialienRoute: typeof LehrmaterialienRoute
  PruefungszentrumFindenRoute: typeof PruefungszentrumFindenRoute
  QualifizierungRoute: typeof QualifizierungRoute
  SitemapRoute: typeof SitemapRoute
  SprachpruefungenRoute: typeof SprachpruefungenRoute
  TrainingsangeboteRoute: typeof TrainingsangeboteRoute
  UeberUnsRoute: typeof UeberUnsRoute
  ZertifikatPruefenRoute: typeof ZertifikatPruefenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lehrmaterialien': {
      id: '/lehrmaterialien'
      path: '/lehrmaterialien'
      fullPath: '/lehrmaterialien'
      preLoaderRoute: typeof LehrmaterialienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefungszentrum-finden': {
      id: '/pruefungszentrum-finden'
      path: '/pruefungszentrum-finden'
      fullPath: '/pruefungszentrum-finden'
      preLoaderRoute: typeof PruefungszentrumFindenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualifizierung': {
      id: '/qualifizierung'
      path: '/qualifizierung'
      fullPath: '/qualifizierung'
      preLoaderRoute: typeof QualifizierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprachpruefungen': {
      id: '/sprachpruefungen'
      path: '/sprachpruefungen'
      fullPath: '/sprachpruefungen'
      preLoaderRoute: typeof SprachpruefungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainingsangebote': {
      id: '/trainingsangebote'
      path: '/trainingsangebote'
      fullPath: '/trainingsangebote'
      preLoaderRoute: typeof TrainingsangeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zertifikat-pruefen': {
      id: '/zertifikat-pruefen'
      path: '/zertifikat-pruefen'
      fullPath: '/zertifikat-pruefen'
      preLoaderRoute: typeof ZertifikatPruefenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AktuellesRoute: AktuellesRoute,
  CampusRoute: CampusRoute,
  KontaktRoute: KontaktRoute,
  LehrmaterialienRoute: LehrmaterialienRoute,
  PruefungszentrumFindenRoute: PruefungszentrumFindenRoute,
  QualifizierungRoute: QualifizierungRoute,
  SitemapRoute: SitemapRoute,
  SprachpruefungenRoute: SprachpruefungenRoute,
  TrainingsangeboteRoute: TrainingsangeboteRoute,
  UeberUnsRoute: UeberUnsRoute,
  ZertifikatPruefenRoute: ZertifikatPruefenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
